/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */

import java.util.regex.*;

public class applicationform3 extends javax.swing.JFrame {

    /**
     * Creates new form applicationform3
     */
    public applicationform3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        lga = new javax.swing.JTextField();
        maiden_name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fname_error = new javax.swing.JLabel();
        mname_error = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sname_error = new javax.swing.JLabel();
        nationality_error = new javax.swing.JLabel();
        state_error = new javax.swing.JLabel();
        lga_error = new javax.swing.JLabel();
        email_error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        address_error = new javax.swing.JLabel();
        maiden_name_error = new javax.swing.JLabel();
        phone_error = new javax.swing.JLabel();
        submit_error = new javax.swing.JLabel();
        age_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
        });

        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        mname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnameKeyReleased(evt);
            }
        });

        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snameKeyReleased(evt);
            }
        });

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageKeyReleased(evt);
            }
        });

        nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityActionPerformed(evt);
            }
        });
        nationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nationalityKeyReleased(evt);
            }
        });

        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        state.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stateKeyReleased(evt);
            }
        });

        lga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgaActionPerformed(evt);
            }
        });
        lga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lgaKeyReleased(evt);
            }
        });

        maiden_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maiden_nameActionPerformed(evt);
            }
        });
        maiden_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maiden_nameKeyReleased(evt);
            }
        });

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressKeyReleased(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });

        jButton1.setText("input your credentials");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Why do you want this job?");
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton2.setText("Summit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("FirstName :");

        jLabel4.setText("MiddleName :");

        jLabel5.setText("SurName :");

        jLabel6.setText("Age :");

        jLabel8.setText("Sex :");

        jRadioButton2.setText("Male");

        jLabel9.setText("Nationality :");

        jLabel10.setText("State Of Origin :");

        jLabel11.setText("LGA :");

        jLabel12.setText("MaidenName :");

        jLabel13.setText("Current Address :");

        jLabel14.setText("emailaddress :");

        jLabel15.setText("Phone Number :");

        fname_error.setForeground(new java.awt.Color(255, 0, 0));
        fname_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fname_errorKeyReleased(evt);
            }
        });

        mname_error.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("ORANGE NIG LTD APPLICATION FORM");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Designed By Marylinda And Maryann");

        sname_error.setForeground(new java.awt.Color(255, 0, 0));
        sname_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sname_errorKeyReleased(evt);
            }
        });

        nationality_error.setForeground(new java.awt.Color(255, 0, 0));
        nationality_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nationality_errorKeyReleased(evt);
            }
        });

        state_error.setForeground(new java.awt.Color(255, 0, 0));
        state_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                state_errorKeyReleased(evt);
            }
        });

        lga_error.setForeground(new java.awt.Color(255, 0, 0));
        lga_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lga_errorKeyReleased(evt);
            }
        });

        email_error.setForeground(new java.awt.Color(255, 0, 0));
        email_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                email_errorKeyReleased(evt);
            }
        });

        jLabel1.setText("Female");

        address_error.setForeground(new java.awt.Color(255, 0, 0));
        address_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                address_errorKeyReleased(evt);
            }
        });

        maiden_name_error.setForeground(new java.awt.Color(255, 0, 0));
        maiden_name_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maiden_name_errorKeyReleased(evt);
            }
        });

        phone_error.setForeground(new java.awt.Color(255, 0, 0));
        phone_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phone_errorKeyReleased(evt);
            }
        });

        submit_error.setForeground(new java.awt.Color(255, 0, 0));
        submit_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                submit_errorKeyReleased(evt);
            }
        });

        age_error.setForeground(new java.awt.Color(255, 0, 0));
        age_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                age_errorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(address_error, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(email_error, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nationality_error, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(state_error, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lga, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lga_error, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maiden_name, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(maiden_name_error, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(phone_error, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(age_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(521, 521, 521))))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sname, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(mname)
                            .addComponent(fname))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(fname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(mname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(submit_error, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fname_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fname))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(mname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sname_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(age_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(nationality_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(state_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(lga_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maiden_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(maiden_name_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(address_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(email_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(phone_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(submit_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(fname.getText().equals("")){
           fname_error.setText("Please input your First name");        
        }
        if(mname.getText().equals("")){
           mname_error.setText("Please input your Middle name");
         }
        if(sname.getText().equals("")){
         sname_error.setText("Please input your surname");
          }
        if(age.getText().equals("")){
          age_error.setText("Please input your age");
          }
        if(nationality.getText().equals("")){
          nationality_error.setText("Please input your nationality");
            }
          if(state.getText().equals("")){
          state_error.setText("Please input your state of origin");
           }
          if(lga.getText().equals("")){
            lga_error.setText("Please input your LGA");
            }
          if(maiden_name.getText().equals("")){
           maiden_name_error.setText("Please input your maiden name");
             }
          if(address.getText().equals("")){
           address_error.setText("Please input your current Address");
             }
          if(email.getText().equals("")){
           email_error.setText("Please input your emailaddress");
             }
          if(phone.getText().equals("")){
           phone_error.setText("Please input your phone number");
          }
        
        
         if(fname.getText().equals("")|| mname.getText().equals("")||sname.getText().equals("")||age.getText().equals("")||nationality.getText().equals("")||
                 state.getText().equals("")||lga.getText().equals("")||maiden_name.getText().equals("")||address.getText().equals("")||
                 email.getText().equals("")||phone.getText().equals("")){
           submit_error.setText("Please Fix error in Form");
            
       }else{
            summit first = new summit();
            first.setVisible(true);
//        }

    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                System.exit(0);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void lgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgaActionPerformed
        // TODO add your handling code here:
        applicationform3 eight = new applicationform3();
        eight.setVisible(true);
    }//GEN-LAST:event_lgaActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
        applicationform3 seven = new applicationform3();
        seven.setVisible(true);
    }//GEN-LAST:event_stateActionPerformed

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
        applicationform3 sixth = new applicationform3();
        sixth.setVisible(true);
    }//GEN-LAST:event_nationalityActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
        applicationform3 fourth = new applicationform3();
        fourth.setVisible(true);
    }//GEN-LAST:event_ageActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        applicationform3 third = new applicationform3();
        third.setVisible(true);
    }//GEN-LAST:event_snameActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        applicationform3 second = new applicationform3();
        second.setVisible(true);
    }//GEN-LAST:event_mnameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        applicationform3 first = new applicationform3();
        first.setVisible(true);
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inputdocuments first = new inputdocuments();
        first.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
        applicationform3 twelve = new applicationform3();
        twelve.setVisible(true);
    }//GEN-LAST:event_phoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
        applicationform3 eleven = new applicationform3();
        eleven.setVisible(true);
    }//GEN-LAST:event_emailActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
        applicationform3 ten = new applicationform3();
        ten.setVisible(true);
    }//GEN-LAST:event_addressActionPerformed

    private void maiden_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maiden_nameActionPerformed
        // TODO add your handling code here:
        applicationform3 nine = new applicationform3();
        nine.setVisible(true);
    }//GEN-LAST:event_maiden_nameActionPerformed

    private void fname_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fname_errorKeyReleased
        // TODO add your handling code here:
        if(mname.getText().equals("")){
           mname_error.setText("Please input your First name");
             }else{
            summit first = new summit();
            first.setVisible(true);
        }
        
    }//GEN-LAST:event_fname_errorKeyReleased

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[a-zA-Z]+";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(fname.getText());
        if(!match.matches()){
            fname_error.setText("Only Alphabets allowed. Name must be longer than 3");
        }else{
            fname_error.setText(null);
        }
       
    }//GEN-LAST:event_fnameKeyReleased

    private void mnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[a-zA-Z]+";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(mname.getText());
        if(!match.matches()){
            mname_error.setText("Only Alphabets allowed. Name must be longer than 3");
        }else{
            mname_error.setText(null);
        }
    }//GEN-LAST:event_mnameKeyReleased

    private void snameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[a-zA-Z]+";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(sname.getText());
        if(!match.matches()){
            sname_error.setText("Only Alphabets allowed. Name must be longer than 3");
        }else{
            sname_error.setText(null);
        }
//    }
//    private void lgaKeyReleased(java.awt.event.KeyEvent evt) {                                  
//        // TODO add your handling code here:
//         String PATTERN = "[a-zA-Z]+";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(lga.getText());
//        if(!match.matches()){
//            lga_error1.setText("Only Alphabets allowed");
//        }else{
//            lga_error1.setText(null);
//        }
//   
    }//GEN-LAST:event_snameKeyReleased

    private void lga_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lga_errorKeyReleased
        // TODO add your handling code here:
//         if(lga.getText().equals("")){
//           lga_error1.setText("Please input your LGA");
//             }else{
//            summit first = new summit();
//            first.setVisible(true);
//        }
//    
    }//GEN-LAST:event_lga_errorKeyReleased

    private void nationality_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationality_errorKeyReleased
//        // TODO add your handling code here:
//        if(nationality.getText().equals("")){
//           nationality_error1.setText("Please input your nationality");
//             }else{
//            summit first = new summit();
//            first.setVisible(true);
//        }
//    }
//         private void nationalityKeyReleased(java.awt.event.KeyEvent evt) {                                  
//        // TODO add your handling code here:
//         String PATTERN = "[a-zA-Z]+";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(sname.getText());
//        if(!match.matches()){
//            nationality_error1.setText("Only Alphabets allowed. Name must be longer than 3");
//        }else{
//            nationality_error1.setText(null);
//        }
    }//GEN-LAST:event_nationality_errorKeyReleased

    private void sname_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sname_errorKeyReleased
//        // TODO add your handling code here:
//         if(sname.getText().equals("")){
//           sname_error1.setText("Please input your surname");
//             }else{
//            summit first = new summit();
//            first.setVisible(true);
//        }
    }//GEN-LAST:event_sname_errorKeyReleased

    private void state_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_state_errorKeyReleased
//        // TODO add your handling code here:
//         if(state.getText().equals("")){
//           state_error.setText("Please input your state");
//             }else{
//            summit first = new summit();
//            first.setVisible(true);
//        }
//      }
//         private void stateKeyReleased(java.awt.event.KeyEvent evt) {                                  
//        // TODO add your handling code here:
//         String PATTERN = "[a-zA-Z]+";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(sname.getText());
//        if(!match.matches()){
//            state_error.setText("Only Alphabets allowed");
//        }else{
//            state_error.setText(null);
//        }
    }//GEN-LAST:event_state_errorKeyReleased

    private void email_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_errorKeyReleased
//        // TODO add your handling code here:
//         if(email.getText().equals("")){
//           email_error.setText("Please input your emailaddress");
//             }else{
//            summit first = new summit();
//            first.setVisible(true);
//        }
//        
    }//GEN-LAST:event_email_errorKeyReleased

    private void ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{1,3}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(age.getText());
        if(!match.matches()){
            age_error.setText("Digits only");
        }else{
            age_error.setText(null);
        }
    }//GEN-LAST:event_ageKeyReleased

    private void nationalityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalityKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z ]{3,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(nationality.getText());
        if(!match.matches()){
            nationality_error.setText("Alphabet only");
        }else{
            nationality_error.setText(null);
        }
    }//GEN-LAST:event_nationalityKeyReleased

    private void stateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z ]{3,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(state.getText());
        if(!match.matches()){
            state_error.setText("Alphabet only");
        }else{
            state_error.setText(null);
        }
    }//GEN-LAST:event_stateKeyReleased

    private void lgaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lgaKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z ]{3,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(lga.getText());
        if(!match.matches()){
            lga_error.setText("Alphabet only");
        }else{
            lga_error.setText(null);
        }
    }//GEN-LAST:event_lgaKeyReleased

    private void address_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address_errorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_address_errorKeyReleased

    private void maiden_name_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maiden_name_errorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_maiden_name_errorKeyReleased

    private void phone_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_errorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_errorKeyReleased

    private void maiden_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maiden_nameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z ]{3,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(maiden_name.getText());
        if(!match.matches()){
            maiden_name_error.setText("Alphabet only");
        }else{
            maiden_name_error.setText(null);
        }
    }//GEN-LAST:event_maiden_nameKeyReleased

    private void addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9ss ]{3,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(address.getText());
        if(!match.matches()){
            address_error.setText("AlphabetNumeric Characters only");
        }else{
            address_error.setText(null);
        }
    }//GEN-LAST:event_addressKeyReleased

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[a-zA-Z0-9]{1,30}[@][a-zA-Z0-9]{1,10}[.][a-zA-Z0-9]{0,5}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(email.getText());
        if(!match.matches()){
            email_error.setText("Invalid Email Format");
        }else{
            email_error.setText(null);
        }
    }//GEN-LAST:event_emailKeyReleased

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{10,30}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(phone.getText());
        if(!match.matches()){
            phone_error.setText("Digits only, At least 10 Characters");
        }else{
            phone_error.setText(null);
        }
    }//GEN-LAST:event_phoneKeyReleased

    private void submit_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submit_errorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_errorKeyReleased

    private void age_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_errorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_age_errorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicationform3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicationform3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicationform3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicationform3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicationform3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel address_error;
    private javax.swing.JTextField age;
    private javax.swing.JLabel age_error;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_error;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel fname_error;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lga;
    private javax.swing.JLabel lga_error;
    private javax.swing.JTextField maiden_name;
    private javax.swing.JLabel maiden_name_error;
    private javax.swing.JTextField mname;
    private javax.swing.JLabel mname_error;
    private javax.swing.JTextField nationality;
    private javax.swing.JLabel nationality_error;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phone_error;
    private javax.swing.JTextField sname;
    private javax.swing.JLabel sname_error;
    private javax.swing.JTextField state;
    private javax.swing.JLabel state_error;
    private javax.swing.JLabel submit_error;
    // End of variables declaration//GEN-END:variables
}
